version: "3"
services:
  vue:
    build: .
    image: vue-dev
    container_name: vue-dev
    working_dir: /home/docker/vue-project
    volumes:
      - ./vue-project:/home/docker/vue-project
      - node_modules:/home/docker/vue-project/node_modules
    ports:
      - 8080:8080
    tty: true
volumes:
  node_modules:
